### ISSUE TITLE
Include a link to the repo

### ISSUE THREAD

**Issue by zoffixznet** [finanalyst/ModuleCitation#1]
It'd be nice if the link to the repo was somewhere on the page, for people to report Issues, etc.

**Comment by finanalyst** [comment]
Dear Zoffix,

I already wrote on this, but was thinking again. Do you mean to put a 
link to repos that have "errors"? Or all modules? or my module?

I thought originally you meant my module (viz. ModuleCitation).

Richard

**Comment by zoffixznet** [comment]
I meant a link from the page with all the data to *this repo*

**Comment by finanalyst** [comment]
I'm trying. This is my first public page with analysis hosted on github.

I put my email at the bottom for feedback. (may be I was too obscure in 
saying 'gmail main domain' instead of 'gmail com'?

What should the link on the page be to?

I'm not trying to be too clever or sophisticated, although I am a bit 
paranoid about my email. I actually don't know as much as I should about 
a git hub repository, or how to handle or create pull requests.

For example, I have forked the Modules page for perl6 under my name on 
github.  I have changed the third paragraph to include a link to my 
Module Citations page. But I don't know what to do next without making 
everyone mad. If I create a pull request, what happens then?

Regards,
Richard
